apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: "result-service"
    port: 5001
    targetPort: 80
    nodePort: 31002
  selector:
    app: result
