apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
  - name: "vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31001
  selector:
    app: vote
  
